[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    'safe-contracts=lib/safe-contracts/contracts'
]

bytecode_hash = 'none'

fs_permissions = [
  { 'access'='read', 'path'='out/GnosisSafeProxyFactory.sol/GnosisSafeProxyFactory.json' },
  { 'access'='read', 'path'='out/GnosisSafe.sol/GnosisSafe.json' },
]
